### ISSUE TITLE
Create the NavHost inside the MainActivity for our Composable Screens

### ISSUE THREAD

**Issue by Kardelio** [Kardelio/Disher#1]
**Note: Please raise your PR against the `main` branch when you are ready!**

### This Issue:

For this issue you need to simply create the NavHost that will wrap our individual screen composables and maybe even create 3 composables within the NavHost that will provide us space to create our 3 screen composable functions (3 screens are described in the `README.md`)

For help or information check out this page: https://developer.android.com/jetpack/compose/navigation

Extra Points:
* Create a navController 
* Setup routes for the 3 screens described in the `README.md`

**Comment by V9vek** [comment]
I looked upon this issue and solved this by adding navHost and other stuff we need 
I am opening a pull request
Kindly check

Thank you 🙏

**Comment by V9vek** [comment]
I have opened up a Pull Request regarding #1  

And please add the required HacktoberFest tag wherever it is needed

**Comment by Hiteshpatel10** [comment]
I can do this job, can you assign me this.

**Comment by Kardelio** [comment]
Apologies @Hiteshpatel10 this issue was already dealt with by another contributor, sorry about that, it is entirely my fault I forgot to close the ticket!
However there are several other tickets that I think you might like in the issues of this repository if you want to try another one?

**Comment by Hiteshpatel10** [comment]
No problem sir, i would like to work on some other issues.
