### ISSUE TITLE
Add copyright licence

### ISSUE THREAD

**Issue by zeusalmighty717** [Kardelio/Disher#13]
>If a repository has no license, then all rights are reserved and it is not Open Source or Free. You cannot modify or redistribute this code without explicit permission from the copyright holder.

[More info](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license)

**Comment by zeusalmighty717** [comment]
Can do a quick PR. What license would you like to add? @Kardelio

**Comment by Kardelio** [comment]
@zeusalmighty717 oooooo very very good question...

honestly not sure, nothing really interesting or useful/important/secretive  in this at all?
So maybe nice and open, apache or GNU ? your call a PR would be nice <3

Thanks for comgin to the stream btw buddy <3 really appreciate it and the energy and support you bring!
